# Generated by Django 5.1.2 on 2025-01-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sections",
            name="access_token",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_access_token",
                to="apps.accesstoken",
            ),
        ),
    ]
