# Generated by Django 5.1.2 on 2025-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_sections_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
