# Generated by Django 5.1.2 on 2025-01-18 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_modules_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Word_Pronunciation_Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word_pronunciation_answers', to='apps.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_user_word_pronunciation_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Word Pronunciation Answer',
                'verbose_name_plural': 'User Word Pronunciation Answers',
                'db_table': 'user_word_pronunciation_answers',
            },
        ),
    ]
