# Generated by Django 5.1.2 on 2025-01-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_user_word_pronunciation_answer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_word_pronunciation_answer',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question'),
        ),
    ]
