# Generated by Django 5.2 on 2025-07-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_teachers_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_word_pronunciation_answer',
            name='unique_question',
        ),
        migrations.AlterUniqueTogether(
            name='user_word_pronunciation_answer',
            unique_together={('user', 'question')},
        ),
    ]
