# Generated by Django 5.1.2 on 2024-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_students_updated_at_alter_teachers_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
