# Generated by Django 5.1.2 on 2024-10-31 14:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_students_address_students_birthday_users_middle_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sections",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name"
            ),
            preserve_default=False,
        ),
    ]
