# Generated by Django 5.1.2 on 2024-11-01 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_alter_students_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("access_token", models.CharField(max_length=1000)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_token_created_by",
                        to="apps.teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Token",
                "verbose_name_plural": "Access Tokens",
                "db_table": "access_token",
            },
        ),
    ]
