# Generated by Django 5.1.2 on 2024-11-06 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_accesstoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Vocabulary Skills", "Vocabulary Skills"),
                            ("Word Pronunciation", "Word Pronunciation"),
                            ("Reading Comprehension", "Reading Comprehension"),
                            ("Sentence Composition", "Sentence Composition"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_created_by",
                        to="apps.teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "modules",
            },
        ),
    ]
