# Generated by Django 5.1.2 on 2024-11-07 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_modules_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleMaterials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("full_path", models.CharField(max_length=255)),
                ("file_url", models.CharField(max_length=255)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials_uploaded_by",
                        to="apps.teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Material",
                "verbose_name_plural": "Module Materials",
                "db_table": "module_materials",
            },
        ),
    ]
