# Generated by Django 5.1.2 on 2024-11-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_modulematerials"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulematerials",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_materials",
                to="apps.modules",
            ),
            preserve_default=False,
        ),
    ]
