# Generated by Django 5.1.2 on 2024-11-07 14:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_modulematerials_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modulematerials",
            name="full_path",
        ),
        migrations.AddField(
            model_name="modulematerials",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="name"
            ),
            preserve_default=False,
        ),
    ]
