# Generated by Django 5.1.2 on 2024-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_alter_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
