# Generated by Django 5.1.2 on 2024-12-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0019_userexperience"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correct_for_question",
                to="apps.answer",
            ),
        ),
    ]
