# Generated by Django 5.1.2 on 2024-12-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0020_question_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
