# Generated by Django 5.1.2 on 2024-12-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0023_question_question_type_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answers",
        ),
    ]
