# Generated by Django 5.1.2 on 2024-12-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0024_remove_question_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="apps.question",
            ),
        ),
    ]
